permalink: /:year/:month/:title.html
markdown: redcarpet
pygments: true

exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock
  - Procfile
  - Guardfile
  - config.rb
  - sass
  - config.ru
  - coffee
  - vendor
  - tmp
  - _drafts

title: flat
url: http://beforeitwasround.com

author: Steve Agalloco
email: steve.agalloco@gmail.com

description: before it was round
keywords: "agalloco, steve agalloco, steve, ruby, rails, eventmachine, github, tophat, airbrake, tweetstream, twitter, charlotte, fanzter, coolspotters"

sitemap_exclude:
  - /sitemap.xml
  - /atom.xml
  - /index.html