permalink: /:year/:month/:title.html
markdown: kramdown

github: [metadata]

kramdown:
  input: GFM
  hard_wrap: false

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate

sass:
  sass_dir: src/scss
  style: :compressed

paginate: 1

exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock
  - src
  - script
  - _drafts
  - design
  - node_modules
  - bower_components
  - bower.json

feed:
  path: atom.xml

baseurl: /
name: flat - The personal website of Steve Agalloco
title: flat
url: http://beforeitwasround.com

author: Steve Agalloco
email: steve.agalloco@gmail.com

description: before it was round
keywords:
  - agalloco
  - steve agalloco
  - steve
  - ruby
  - rails
  - jruby
  - sinatra
  - eventmachine
  - github
  - rubygem
  - tophat
  - airbrake
  - tweetstream
  - twitter
  - charlotte
  - brokerage
  - api
  - finance
  - quote
  - options
  - tradier
  - fintech
