permalink: /:year/:month/:title.html
markdown: redcarpet
pygments: true

exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock
  - Procfile
  - config.rb
  - sass
  - config.ru
  - coffee

title: flat
url: http://beforeitwasround.com

author: Steve Agalloco
email: steve.agalloco@gmail.com

description: Before It Was Round
keywords:
  - agalloco
  - steve agalloco
  - steve
  - fanzter
  - coolspotters
  - simplesports
  - ethicon
  - github
  - ruby
  - ruby on rails
  - tophat
  - airbrake
  - tweetstream
  - twitter
  - charlotte
