permalink: /:year/:month/:title.html
markdown: redcarpet
pygments: true

exclude: ["CNAME", "README", "Gemfile", "Gemfile.lock", "Procfile", "config.rb", "sass", "config.ru"]

title: flat
url: http://beforeitwasround.com

description: Before It Was Round
keywords: jekyll, template, blog
author: Steve Agalloco
email: steve.agalloco@gmail.com
analytics_id: # Google Analytics ID: UA-xxx-xxx
