permalink: /:year/:month/:title.html
markdown: rdiscount
pygments: true
safe: true
lsi: false

rdiscount:
  extensions: []

exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - config.rb
  - vendor
  - js
  - css
  - src
  - _drafts

title: flat
url: http://beforeitwasround.com

author: Steve Agalloco
email: steve.agalloco@gmail.com

description: before it was round
keywords:
  - agalloco
  - steve agalloco
  - steve
  - ruby
  - rails
  - jruby
  - sinatra
  - eventmachine
  - github
  - rubygem
  - tophat
  - airbrake
  - tweetstream
  - twitter
  - charlotte
  - brokerage
  - api
  - finance
  - quote
  - options

sitemap_exclude:
  - /sitemap.xml
  - /atom.xml
  - /index.html
  - /404.html
