destination: ./_site
auto: false
markdown: rdiscount
pygments: true


#
# Site configuration
#
permalink: /:year/:month/:title.html
url: http://localhost:4000
title: flat
description: Before It Was Round
keywords: jekyll, template, blog
author: Steve Agalloco
email: steve.agalloco@gmail.com
analytics_id: # Google Analytics ID: UA-xxx-xxx
