permalink: /:year/:month/:title.html
markdown: kramdown
highlighter: pygments

gems:
  - jekyll-sitemap

exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - config.rb
  - vendor
  - js
  - css
  - src
  - design
  - script
  - _drafts
  - build
  - node_modules
  - bower_components
  - gulpfile.js
  - bower.json
  - package.json

title: flat
url: http://beforeitwasround.com

author: Steve Agalloco
email: steve.agalloco@gmail.com

description: before it was round
keywords:
  - agalloco
  - steve agalloco
  - steve
  - ruby
  - rails
  - jruby
  - sinatra
  - eventmachine
  - github
  - rubygem
  - tophat
  - airbrake
  - tweetstream
  - twitter
  - charlotte
  - brokerage
  - api
  - finance
  - quote
  - options
  - tradier
  - fintech
